### ISSUE TITLE
Status of Ecology and new repos

### ISSUE THREAD

**Issue by mkborregaard** [svaksha/Julia.jl#105]
Hi,
It is hard to find "Ecology", as it is an entry under both Biology and Earth Sciences, with different things listed under each. Maybe nice to put it under one of them, and then have  a local link under the other? The problem is, of course, that Ecology isn't easy to place into either - it's position under earth science or biology varies from university to university.

Also, you might check out our registered organisation for ecology in Julia, https://github.com/EcoJulia/ , and our repos https://github.com/EcoJulia/SpatialEcology.jl and https://github.com/EcoJulia/GBIF.jl .

Thanks!

**Comment by svaksha** [comment]
Hi, you are right about the inter-disciplinary nature of some (sub)-categories that makes it hard to specifically slot them in a single category. However, please feel free to add your Org (& packages) to an existing page - feel free to slot it in the category you think it is best suited under and submit a pull request. I will gladly merge it. Thanks.

**Comment by mkborregaard** [comment]
Great, thanks. Would you merge a pull request that put ecology as one cohesive category?

**Comment by svaksha** [comment]
As long as the packages "fit" (for lack of a better term) there, it should be fine.  Please submit a PR for your changes.

Later, if there are many biology, geography, and Earth science packages, we can create a new 'Ecology' page.

PS: Aside, I like the Tiddlywiki concept of "tagging" tiddlers (which solves the category overlap issue, somewhat) and also using various macros, but the markdown (used by github) does not support it. And it would be quite confusing and painful to read tiddlers in the raw format. (/end thinking out loud)
