### ISSUE TITLE
Add my package for Analytical Chemistry

### ISSUE THREAD

**Issue by caseykneale** [svaksha/Julia.jl#159]
Just found this list, 

I have been working on a toolset for chemometrics(chemical data + data science)
https://github.com/caseykneale/ChemometricsTools.jl

I'd appreciate it if this were added to the list!

**Comment by svaksha** [comment]
Hi @caseykneale, 
Sure, please submit a PR and I will gladly merge it. If if helps, here are the contributing instructions: https://github.com/svaksha/Julia.jl#bugreport-pullrequest
