### ISSUE TITLE
classification of optimization

### ISSUE THREAD

**Issue by mlubin** [svaksha/Julia.jl#21]
I don't think "Optimization" is properly classified under benchmarks. I would suggest moving this section to a "numerical optimization" section under mathematics which includes JuliaOpt and all related projects. Also, Cbc.jl, JuMP, and JuMPeR are operations research/optimization projects, not linear algebra.

**Comment by IainNZ** [comment]
Other things I spotted:
* an OR section: https://github.com/svaksha/Julia.jl/blob/master/Statistics.md#operations-research
* a Numerical Analysis https://en.wikipedia.org/wiki/Category:Numerical_analysis that contains Knitro

**Comment by IainNZ** [comment]
Maybe easiest thing to do, in general actually, would be to mirror organizations where they exist - so all JuliaOpt packages could be kept together, JuliaWeb, etc.

**Comment by svaksha** [comment]
@mlubin, As @IainNZ suggested, would 'Optimization' be better suited as a sub-section under Operations Research or maybe Statistics (where it was previously)? 
I've moved "Cbc.jl, JuMP, and JuMPeR" to the OR section, will be reflected when I push to master.

@IainNZ, good point. Just to understand, are you suggesting JuliaWeb be moved elsewhere or were you suggesting all the Optimization packages be listed like its been done for [JuliaWeb](https://github.com/svaksha/Julia.jl/blob/master/Web-Server.md#yajo---juliaweb)? Atm, the orgs get listed under the broad category they fall in - example, `JuliaQuant` org gets listed under the Valuation (finance) section on the Statistics page as most of the packages tend to be statistics heavy.

**Comment by IainNZ** [comment]
@svaksha , the second, like JuliaWeb

**Comment by svaksha** [comment]
Ok, done: 1bf6d2791b3c4f37a83b27f3f29b1a7c804c7146
