### ISSUE TITLE
SimJulia miscategorized

### ISSUE THREAD

**Issue by IainNZ** [svaksha/Julia.jl#25]
Shouldn't be under "Build Automation", probably should be in "Operations Research"

**Comment by IainNZ** [comment]
Its also listed under `Web`

**Comment by svaksha** [comment]
Thanks, Fixed in 0a6708e539f489ae811de12735cb570e0c7fa556

**Comment by IainNZ** [comment]
I'm not sure if that commit got pushed

**Comment by svaksha** [comment]
I fixed the merge conflict, so please check if its reflected
