### ISSUE TITLE
packege renamed

### ISSUE THREAD

**Issue by DANA-Laboratory** [svaksha/Julia.jl#26]
hi
refer to this:
https://github.com/svaksha/Julia.jl/commit/398fa9fac117082a854a53fc3af09baca5569597
please replace:
`
[TypeInheritance.jl](https://github.com/DANA-Laboratory/TypeInheritance.jl) :: Adds Inheritance to julia composite type.
`
with:
`
[DotPlusInheritance.jl](https://github.com/DANA-Laboratory/DotPlusInheritance.jl)::Expression parser that simulates type inheritance
`
thanks

**Comment by svaksha** [comment]
Thanks for the ping. Fixed: https://github.com/svaksha/Julia.jl/commit/534c196a766acb784fcb28bf1e4762f7d7f38e70#diff-775c92508e9344f37332f4a4f24a81dfR62
