### ISSUE TITLE
A misc repo

### ISSUE THREAD

**Issue by jhlq** [svaksha/Julia.jl#35]
Have gathered some files and made a short descriptive index, as requested: https://github.com/jhlq/fys

There is no one theme here, so... where do you want it?

**Comment by svaksha** [comment]
On Wed, Jun 17, 2015 at 8:36 AM, Marcus Appelros
<notifications@github.com> wrote:
>
> Have gathered some files and made a short descriptive index, as requested: https://github.com/jhlq/fys
>
> There is no one theme here, so... where do you want it?

Hi,
TBH, I dont know what `fys` means and was unable to figure out what
the package does - is it related to Physics (it says "Physics and
misc")? I think package authors should have the final say to name
their packages but for a lay person going to use your package a
meaningful/relevant name makes it easier to grok what the code is
about from the package name. Please see the Julia naming guidelines[1]
and for a detailed guideline, there is the Python naming convention
pep[2].
Also, if there is no license[3] in your codebase, it cannot be forked
or modified by others.

[1] https://github.com/JuliaLang/julia/blob/5c065e79c929885debba660f8143e2bee05eeab2/doc/manual/packages.rst#guidelines-for-naming-a-package
[2] https://www.python.org/dev/peps/pep-0423/
[3] http://choosealicense.com/no-license/

Hope That Helps!
Thanks, SVAKSHA ॥  http://about.me/svaksha  ॥

**Comment by jhlq** [comment]
It's not a package, linked the mindfulness program in our earlier
conversation and you asked me to put it in a repo so it could be added
here. Fys is shorthand for fysik (which is physics) because initially used
the repo to save physical scripts

**Comment by svaksha** [comment]
Ok, then can I add it to the Physics page? Or if you wish to list them elsewhere do say so.

**Comment by jhlq** [comment]
Yes thats great

**Comment by svaksha** [comment]
Will do that!
