### ISSUE TITLE
Computer-Vision misnamed?

### ISSUE THREAD

**Issue by timholy** [svaksha/Julia.jl#46]
In Computer-Vision I'd expect to find face recognition algorithms, object tracking, etc. But Computer-Vision really contains a number of graphics & plotting-related packages, plus I/O packages. Maybe consider changing the name?

**Comment by svaksha** [comment]
Ah, you noticed the name change from Computer-Graphics to Computer-Vision. :) Will revert with the next push.

**Comment by svaksha** [comment]
Fixed : https://github.com/svaksha/Julia.jl/commit/9a433c2c9ee93fa5f19ca870ab3e2f545d458b38

**Comment by timholy** [comment]
Thanks!
