### ISSUE TITLE
Can we translate this repo to Chinese in JuliaCN?

### ISSUE THREAD

**Issue by Roger-luo** [svaksha/Julia.jl#60]
Hi, svaksha,

Would it be allowed to translate this repo to Chinese in [JuliaCN](https://github.com/JuliaCN) or maybe in Chinese version of julia docs?

And what kind of rules should we obey?

Best Regards,
Roger Luo

**Comment by svaksha** [comment]
Hi @Roger-luo , please feel free to translate the repo into chinese. Translations are always a nice to have addition. When done, do update this issue page so I can include a link to it on the main page. 
Best, S

**Comment by Roger-luo** [comment]
Sure, thanks! :-)

**Comment by svaksha** [comment]
Leaving it open so that you can submit the link PR when done.

**Comment by svaksha** [comment]
Fixed, https://github.com/svaksha/Julia.jl/pull/61
