### ISSUE TITLE
Quantumoptics.jl

### ISSUE THREAD

**Issue by bastikr** [svaksha/Julia.jl#62]
Can you please move Quantumoptics.jl from QuantumChemistry to the Quantum Mechanics section in Physics? I think it would fit there much better.

**Comment by bastikr** [comment]
And now I also changed the name of the project from Quantumoptics.jl to QuantumOptics.jl to follow the convention used for julia packages.  Sorry for the additional work:(

**Comment by svaksha** [comment]
Hi, thanks for the information. Fixed.
