### ISSUE TITLE
Illegal quoting in line 6

### ISSUE THREAD

**Issue by Roger-luo** [svaksha/Julia.jl#64]
The db.csv cannot be previewed on github. And it seems to have such an error?

**Comment by svaksha** [comment]
Thanks for the BR, its been fixed in the latest commit. The repo has been deleted after @one-more-minute changed his username.

**Comment by svaksha** [comment]
@tbreloff, it seems like I messed up the csv rendering and created more columns.
´´´
It looks like row 6 should actually have 5 columns, instead of 9. 
´´´
Any ideas on how to fix this?
