### ISSUE TITLE
WaveToy should not be under games?

### ISSUE THREAD

**Issue by PallHaraldsson** [svaksha/Julia.jl#66]
+See Poisson, Pound, Vega,
+"The Motion of Point Particles in Curved Spacetime", LRR-2011-7 (2011),
+DOI 10.12942/lrr-2011-7
+
+However, we use the opposite sign convention for the charge q.

I didn't clearly see what the code is for.. but this probably should go under "Physics"?

**Comment by svaksha** [comment]
Thanks, hope that fixes it.
